### ISSUE TITLE
Arch support

### ISSUE THREAD

**Issue by psalkowski** [yurilchuk/utorrent-kubernetes#57]
It looks like it doesn't work for ARCH, because in Dockerfile, you download confd dedicated for amd64: https://github.com/yurilchuk/utorrent-kubernetes/blob/master/Dockerfile#L26

Could you please solve it?

**Comment by psalkowski** [comment]
@yurilchuk could you please merge it? :)

**Comment by yurilchuk** [comment]
Sorry by delay. Already merged! :)
